### ISSUE TITLE
document is not defined (via ReferenceError)

### ISSUE THREAD

**Issue by niclake** [goblindegook/littlefoot#1925]
Hey all.

I'm currently in the process of switching my site over to 11ty. In the process, I decided to use the `npm` package, vs. the CDN usage I'd been doing previously.

When I install it, then attempt to require it, I get an error at runtime (`<===` are mine for indication):

```
[11ty] Eleventy CLI Fatal Error: (more in DEBUG output)
[11ty] 1. Error in your Eleventy config file '.eleventy.js'. (via EleventyConfigError)
[11ty] 2. document is not defined (via ReferenceError) <===
[11ty] 
[11ty] Original error stack trace: ReferenceError: document is not defined
[11ty]     at Object.<anonymous> (/Users/niclake/github/niclake-11ty/node_modules/littlefoot/dist/littlefoot.cjs.js:1:6624) <===
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
[11ty]     at Module.load (node:internal/modules/cjs/loader:1207:32)
[11ty]     at Module._load (node:internal/modules/cjs/loader:1023:12)
[11ty]     at Module.require (node:internal/modules/cjs/loader:1235:19)
[11ty]     at require (node:internal/modules/helpers:176:18)
[11ty]     at Object.<anonymous> (/Users/niclake/github/niclake-11ty/.eleventy.js:3:20)
[11ty]     at Module._compile (node:internal/modules/cjs/loader:1376:14)
[11ty]     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
```

When I dug in to the package, it appears to be happening at the `document.addEventListener` chunk of code.

I don't *think* I'm doing anything wrong here, but if anyone has any suggestions, I'm all ears.

**Comment by niclake** [comment]
Full steps I ran:

- `npm install littlefoot`
- In my `.eleventy.js` file (which is where I've been requiring other modules), I added `const littlefoot = require('littlefoot');`
- `npx @11ty/eleventy --serve` to build and run locally

Upon getting the error and triaging, I:

- Tried reinstalling `littlefoot`
- Tried requiring `littlefoot.js` (got a different error message)
- Deleted my `node_modules` and `package-lock.json`, cleared my cache, and `npm install`

**Comment by niclake** [comment]
What I ended up doing to make this work with 11ty:

- Use the `addPassthroguCopy()` method without a `require()`
    - `eleventyConfig.addPassthroughCopy({ "node_modules/littlefoot/dist/littlefoot.js": "assets/js/littlefoot.js" });`
- Included the `<script>` tags at the root of my site like I would w/ the CDN option

A feasible workaround, I guess. I'd love to have something in-line, but I understand if you'd rather just close this.

**Comment by goblindegook** [comment]
Hi, unfortunately I'm not familiar with how 11ty works. By including it in the `.eleventy.js` file, will it be trying to import and instantiate littlefoot from a Node process? If that's the case then it will not work as the library was made to run on the browser side.

**Comment by tcn33** [comment]
In case anyone comes across this as I did while trying to get Littlefoot working with Astro, here's what worked for me:

- `npm install littlefoot`
- Added to the top of my `Layout.astro` file:` import "@styles/littlefoot.css";`
- Further down (I put mine inside the `<body>` tag, but AFAIK it just needs to be outside the frontmatter) I imported the function and wrapped it inside an event listener since the theme I'm using does some SPA-like stuff:
```javascript
      import { littlefoot } from "littlefoot";

      document.addEventListener('astro:page-load', () => {
        littlefoot();
      });
```
Hope this helps.
